[package]
edition = "2018"
build = "./common/build/build.rs"
name = "rldp"
version = "0.7.47"
description = "RLDP library"

[workspace]

[dependencies]
async-trait = "0.1.22"
base64 = "0.11.0"
failure = "0.1.6"
log = "0.4.8"
rand = "0.7.2"
raptorq = { version = "1.2.1", path = "raptorq" }
tokio = { version = "1.5.0", features = ["rt-multi-thread"] }

lockfree = { git = "https://github.com/tonlabs/lockfree.git" }
adnl = { git = "https://github.com/tonlabs/ton-labs-adnl", features = ["node"] }
ton_api = { git = "https://github.com/tonlabs/ton-labs-tl.git", package = "ton_api" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }

[dev-dependencies]
arrayref = "0.3.5"
external-ip = "4.1.0"
hex = "^0"
log4rs = "0.8.3"
overlay = { git = "https://github.com/tonlabs/ton-labs-overlay.git" }
serde_json = "1.0.41"
sha2 = "0.8.0"

[features]
compression = ["adnl/compression"]
telemetry = ["adnl/telemetry"]

