[package]
build = './common/build/build.rs'
description = 'RLDP library'
edition = '2018'
name = 'rldp'
resolver = '2'
version = '0.7.60'

[workspace]


[dependencies]
async-trait = '0.1'
base64 = '0.13'
failure = '0.1'
log = '0.4'
rand = '0.7'
adnl = { features = [ 'node' ], git = 'https://github.com/tonlabs/ton-labs-adnl', tag = '0.7.65' }
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
raptorq = { path = 'raptorq', version = '1.2.1' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl', package = 'ton_api', tag = '0.2.120' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types', tag = '1.10.12' }

[dev-dependencies]
external-ip = '4.1'
hex = '0.4'
log4rs = '1.0'
serde_json = '1.0'
sha2 = '0.9'
overlay = { git = 'https://github.com/tonlabs/ton-labs-overlay', tag = '0.6.49' }

[features]
compression = [ 'adnl/compression' ]
telemetry = [ 'adnl/telemetry' ]
telemetry_test_only = [ 'adnl/telemetry', 'overlay/telemetry' ]

